# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Remove existing build files
      run: | 
        echo ${{ secrets.SSH_KEY }} | base64 -d > sshkey
        chmod 400 sshkey 
        ssh -o StrictHostKeyChecking=no -i sshkey ska78657@34.93.195.237 rm -rf /var/www/beta.engagemusic.io/html/build
